<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KelasSeeder extends Seeder
{
    public function run()
    {
        DB::table('kelas')->insert([
            [
                'id_kelas' => 'A0000',
                'nama_kelas' => 'Semeser Atas',
                'mata_proyek' => '',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'A0001',
                'nama_kelas' => 'Semeser Atas',
                'mata_proyek' => '',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'A1ALIN',
                'nama_kelas' => 'A1',
                'mata_proyek' => 'Proyek Aljabar Linear',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'A2ALIN',
                'nama_kelas' => 'A2',
                'mata_proyek' => 'Proyek Aljabar Linear',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B1ALIN',
                'nama_kelas' => 'B1',
                'mata_proyek' => 'Proyek Aljabar Linear',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B2ALIN',
                'nama_kelas' => 'B2',
                'mata_proyek' => 'Proyek Aljabar Linear',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_kelas' => 'CALIN',
                'nama_kelas' => 'C',
                'mata_proyek' => 'Proyek Aljabar Linear',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_kelas' => 'A1BASDA',
                'nama_kelas' => 'A1',
                'mata_proyek' => 'Proyek Basis Data',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'A2BASDA',
                'nama_kelas' => 'A2',
                'mata_proyek' => 'Proyek Basis Data',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B1BASDA',
                'nama_kelas' => 'B1',
                'mata_proyek' => 'Proyek Basis Data',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B2BASDA',
                'nama_kelas' => 'B2',
                'mata_proyek' => 'Proyek Basis Data',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'CBASDA',
                'nama_kelas' => 'C',
                'mata_proyek' => 'Proyek Basis Data',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'A1RPL',
                'nama_kelas' => 'A1',
                'mata_proyek' => 'Proyek Rekayasa Perangkat Lunak',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'A2RPL',
                'nama_kelas' => 'A2',
                'mata_proyek' => 'Proyek Rekayasa Perangkat Lunak',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B1RPL',
                'nama_kelas' => 'B1',
                'mata_proyek' => 'Proyek Rekayasa Perangkat Lunak',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B2RPL',
                'nama_kelas' => 'B2',
                'mata_proyek' => 'Proyek Rekayasa Perangkat Lunak',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'CRPL',
                'nama_kelas' => 'C',
                'mata_proyek' => 'Proyek Rekayasa Perangkat Lunak',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'A1SO',
                'nama_kelas' => 'A1',
                'mata_proyek' => 'Proyek Sistem Operasi',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'A2SO',
                'nama_kelas' => 'A2',
                'mata_proyek' => 'Proyek Sistem Operasi',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B1SO',
                'nama_kelas' => 'B1',
                'mata_proyek' => 'Proyek Sistem Operasi',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B2SO',
                'nama_kelas' => 'B2',
                'mata_proyek' => 'Proyek Sistem Operasi',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'CSO',
                'nama_kelas' => 'C',
                'mata_proyek' => 'Proyek Sistem Operasi',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'A1PSM',
                'nama_kelas' => 'A1',
                'mata_proyek' => 'Proyek Sistem Multimedia',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'A2PSM',
                'nama_kelas' => 'A2',
                'mata_proyek' => 'Proyek Sistem Multimedia',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B1PSM',
                'nama_kelas' => 'B1',
                'mata_proyek' => 'Proyek Sistem Multimedia',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B2PSM',
                'nama_kelas' => 'B2',
                'mata_proyek' => 'Proyek Sistem Multimedia',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'CPSM',
                'nama_kelas' => 'C',
                'mata_proyek' => 'Proyek Sistem Multimedia',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'A1PBKK',
                'nama_kelas' => 'A1',
                'mata_proyek' => 'Proyek Pemrograman Berbasis Kerangka Kerja',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'A2PBKK',
                'nama_kelas' => 'A2',
                'mata_proyek' => 'Proyek Pemrograman Berbasis Kerangka Kerja',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B1PBKK',
                'nama_kelas' => 'B1',
                'mata_proyek' => 'Proyek Pemrograman Berbasis Kerangka Kerja',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B2PBKK',
                'nama_kelas' => 'B2',
                'mata_proyek' => 'Proyek Pemrograman Berbasis Kerangka Kerja',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'CPBKK',
                'nama_kelas' => 'C',
                'mata_proyek' => 'Proyek Pemrograman Berbasis Kerangka Kerja',
                'semester' => 'Ganjil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'A1SDA',
                'nama_kelas' => 'A1',
                'mata_proyek' => 'Proyek Struktur Data dan Algoritma',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'A2SDA',
                'nama_kelas' => 'A2',
                'mata_proyek' => 'Proyek Struktur Data dan Algoritma',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B1SDA',
                'nama_kelas' => 'B1',
                'mata_proyek' => 'Proyek Struktur Data dan Algoritma',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B2SDA',
                'nama_kelas' => 'B2',
                'mata_proyek' => 'Proyek Struktur Data dan Algoritma',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'CSDA',
                'nama_kelas' => 'C',
                'mata_proyek' => 'Proyek Struktur Data dan Algoritma',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'A1PBO',
                'nama_kelas' => 'A1',
                'mata_proyek' => 'Proyek Pemrograman Berbasis Objek',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'A2PBO',
                'nama_kelas' => 'A2',
                'mata_proyek' => 'Proyek Pemrograman Berbasis Objek',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B1PBO',
                'nama_kelas' => 'B1',
                'mata_proyek' => 'Proyek Pemrograman Berbasis Objek',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B2PBO',
                'nama_kelas' => 'B2',
                'mata_proyek' => 'Proyek Pemrograman Berbasis Objek',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'CPBO',
                'nama_kelas' => 'C',
                'mata_proyek' => 'Proyek Pemrograman Berbasis Objek',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'A1PWEB',
                'nama_kelas' => 'A1',
                'mata_proyek' => 'Proyek Pemrograman Web',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'A2PWEB',
                'nama_kelas' => 'A2',
                'mata_proyek' => 'Proyek Pemrograman Web',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B1PWEB',
                'nama_kelas' => 'B1',
                'mata_proyek' => 'Proyek Pemrograman Web',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B2PWEB',
                'nama_kelas' => 'B2',
                'mata_proyek' => 'Proyek Pemrograman Web',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'CPWEB',
                'nama_kelas' => 'C',
                'mata_proyek' => 'Proyek Pemrograman Web',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'A1BASDAL',
                'nama_kelas' => 'A1',
                'mata_proyek' => 'Proyek Basis Data Lanjut',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'A2BASDAL',
                'nama_kelas' => 'A2',
                'mata_proyek' => 'Proyek Basis Data Lanjut',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B1BASDAL',
                'nama_kelas' => 'B1',
                'mata_proyek' => 'Proyek Basis Data Lanjut',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B2BASDAL',
                'nama_kelas' => 'B2',
                'mata_proyek' => 'Proyek Basis Data Lanjut',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'CBASDAL',
                'nama_kelas' => 'C',
                'mata_proyek' => 'Proyek Basis Data Lanjut',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'A1JARKOM',
                'nama_kelas' => 'A1',
                'mata_proyek' => 'Proyek Jaringan Komputer',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'A2JARKOM',
                'nama_kelas' => 'A2',
                'mata_proyek' => 'Proyek Jaringan Komputer',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B1JARKOM',
                'nama_kelas' => 'B1',
                'mata_proyek' => 'Proyek Jaringan Komputer',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kelas' => 'B2JARKOM',
                'nama_kelas' => 'B2',
                'mata_proyek' => 'Proyek Jaringan Komputer',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_kelas' => 'CJARKOM',
                'nama_kelas' => 'C',
                'mata_proyek' => 'Proyek Jaringan Komputer',
                'semester' => 'Genap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ]);
    }
}
